name: Testing Laravel

on:
  push:
    branches: [ "Kaizuki" ]
  pull_request:
    branches: [ "Kaizuki" ]

jobs:
   Laravel_Run_On_Ubuntu:
    name: testing OS ubuntu
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node: [ 14, 16, 18 ]
            php: [ 8.1, 8.0, 7.4 ]
    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
    
    - name: php ${{ $matrix.php }} Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      run: php -v
    - name: Install Composer
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Node ${{ matrix.node }} testing
      run: npm ci
      run: npm test
      
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
